/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sggs(props) {

 


  const { nodes, materials } = useGLTF('models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      {/* Buses  */}
      <mesh geometry={nodes.Buses.geometry} material={materials.CarEdges} position={[1.976, 0.221, 4.511]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_364001.geometry} material={materials.Bus1} />
        <mesh geometry={nodes.Object_372001.geometry} material={materials.blac} />
        <mesh geometry={nodes.Object_373001.geometry} material={materials.Edges} />
      </mesh>

      {/* Rnxg */}
      <mesh geometry={nodes.rnxg.geometry} material={materials.World_ap} position={[0.142, -0.013, -1.47]} rotation={[Math.PI / 2, 0, -0.818]} />

      {/* Girls Hostel */}
      <mesh geometry={nodes.Hostel_Girls.geometry} material={materials.lambert12SG} position={[9.892, 0, 5.303]} rotation={[Math.PI / 2, 0, -2.48]} />

      {/* Boys Hostel */}
      <mesh geometry={nodes.Boys_hostel.geometry} material={materials['initialShadingGroup.001']} position={[-12.856, 0, 2.166]} rotation={[-Math.PI / 2, 0, 0.861]}>
        <mesh geometry={nodes.hostelpart2.geometry} material={materials['initialShadingGroup.001']} />
      </mesh>

      {/* Ground all connected */}
      <group position={[1.928, 0, 1.021]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.Green} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.GreenLight} />
        <group position={[2.633, 0.659, 7.297]} rotation={[0, 0.053, 0]}>
          <mesh geometry={nodes.Cube001.geometry} material={materials.Concrete} />
          <mesh geometry={nodes.Cube001_1.geometry} material={materials.gray} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.blue} />
          <mesh geometry={nodes.sggs_name.geometry} material={materials.Glowing} position={[-0.719, 0.019, 0.198]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[2.588, 0.003, 6.363]} rotation={[0, 0.035, 0]}>
          <mesh geometry={nodes.Plane001.geometry} material={materials.Concrete} />
          <mesh geometry={nodes.Plane001_1.geometry} material={materials['Road Black']} />
          <mesh geometry={nodes.Plane001_2.geometry} material={materials['Road White']} />
          <mesh geometry={nodes.Plane001_3.geometry} material={materials.Footpath} />
          <mesh geometry={nodes.Plane001_4.geometry} material={materials.Green} />

          {/* Light pole */}
          <mesh geometry={nodes.Light_Poll.geometry} material={materials['Pole.001']} position={[0.023, 0.79, -1.638]} rotation={[0, 1.535, 0]} />


        </group>

        {/* Tree 1 */}
        <mesh geometry={nodes.Tree1.geometry} material={materials.Leaves} position={[1.037, -0.048, 6.859]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.lower1.geometry} material={materials.material_0} />
        </mesh>

        {/* Tree 2 */}
        <mesh geometry={nodes.Tree2.geometry} material={materials.Wood} position={[1.063, 0.451, 6.023]} rotation={[Math.PI, -0.033, Math.PI]}>
          <mesh geometry={nodes.upper2.geometry} material={materials.Leaves} />
        </mesh>
      </group>

      {/* Entc Big Building */}
      <mesh geometry={nodes.Entc.geometry} material={materials.lambert44SG} position={[-1.498, 0.007, 3.634]} rotation={[-Math.PI / 2, 0, -2.26]}>
      </mesh>

      {/* Entc Building Kaman */}
      <mesh geometry={nodes.building_kaman.geometry} material={materials.lambert51SG} position={[-1.498, 0.007, 3.434]} rotation={[-Math.PI / 2, 0, -2.26]} />

      {/* cse Small building part */}
      <mesh geometry={nodes.small_building.geometry} material={materials.lambert35SG} position={[-3.079, 0, -4.408]} rotation={[-Math.PI / 2, 0, -0.707]} />

      <mesh geometry={nodes.small_building.geometry} material={materials.lambert35SG} position={[-4.498, 0, -3]} rotation={[-Math.PI / 2, 0, -0.707]} />

      <mesh geometry={nodes.small_building.geometry} material={materials.lambert35SG} position={[-3.079, 0, -4.408]} rotation={[-Math.PI / 2, (Math.PI *130)/180, 0]} />

      {/* Basketball ground */}
      <group position={[-8.951, 0.004, 2.073]} rotation={[-Math.PI / 2, 0, -2.328]}>
        <mesh geometry={nodes.bp1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.bp1_1.geometry} material={materials['Material.008']} />
        {/* Basketball racket1 */}
        <mesh geometry={nodes.basketballCollection.geometry} material={materials['material_0.001']} position={[1.12, 0.003, 0.021]} rotation={[0, 0, 0.004]}>
          <mesh geometry={nodes.b1.geometry} material={materials['Material.006']} position={[-0.175, 0, 0.627]} rotation={[-1.788, -1.567, 2.925]} />
          <mesh geometry={nodes.b2.geometry} material={materials['Material.005']} position={[-0.175, 0, 0.627]} rotation={[-1.788, -1.567, 2.925]} />
          <mesh geometry={nodes.b3.geometry} material={materials['material_0.001']} position={[-0.175, 0, 0.627]} rotation={[-1.788, -1.567, 2.925]} />
          <mesh geometry={nodes.b4.geometry} material={materials.Cylinder__0} position={[-0.26, 0, 0.496]} />
          <mesh geometry={nodes.b5.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.b6.geometry} material={materials['Material.005']} position={[-0.26, 0, 0.541]} />
        </mesh>
      </group>
      <group position={[3.997, -0.002, 1.763]}>
        <mesh geometry={nodes.Circle002.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.Concrete} />
        <mesh geometry={nodes.Circle002_2.geometry} material={materials.HouseRoof4} />
        <mesh geometry={nodes.Circle002_3.geometry} material={materials.Burger_Shop_Coffee_HouseBlack} />
        <mesh geometry={nodes.Circle002_4.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Circle002_5.geometry} material={materials.lambert44SG} />
        <mesh geometry={nodes.Circle002_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Poll.geometry} material={materials.med_diffuse} position={[2.535, -0.113, 0.423]} rotation={[-Math.PI / 2, 0, 0]} />
        <group position={[0.462, 1.026, 0.556]}>
          <mesh geometry={nodes.Sphere_1.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Sphere_2.geometry} material={materials.glass2} />
        </group>
      </group>

      {/* A complex */}
      <mesh geometry={nodes.a_complex.geometry} material={materials.lambert8SG} position={[0.892, 0.022, 0.996]} rotation={[-Math.PI / 2, 0, 2.415]} />


    </group>
  )
}

useGLTF.preload('models/scene.gltf')
